[phases.setup]
nixPkgs = ["nodejs_20", "graphicsmagick", "ghostscript", "poppler_utils"]

[phases.install]
cmds = ["npm install -g pnpm@10 && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
